name: Compilar SimpMusic iOS

on:
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      # --- AHORA ESTO NO CANCELARÁ EL PROCESO SI NO ENCUENTRA EL ARCHIVO ---
      - name: Prevenir errores de permisos
        run: |
          chmod +x gradlew || true
          chmod +x android/gradlew || true
          find . -type f -name "*.sh" -exec chmod +x {} \; || true

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias de Flutter
        run: flutter pub get

      - name: Compilar iOS (Sin firma para instalar en Windows)
        run: |
          flutter build ios --release --no-codesign
          
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/
          
          zip -qr SimpMusic.ipa Payload

      - name: Subir archivo .ipa para descargar
        uses: actions/upload-artifact@v4
        with:
          name: SimpMusic-iOS-IPA
          path: SimpMusic.ipa
          retention-days: 7
