name: Compilar SimpMusic macOS

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Java (Requerido para compilar)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Dar permisos de ejecución a Gradle
        run: chmod +x gradlew || true

      - name: Compilar y empaquetar la app de macOS
        # Este es el comando oficial de Compose Desktop para crear el instalador
        run: ./gradlew packageDistributionForCurrentOS --no-daemon

      - name: Subir el instalador .dmg para descargar
        uses: actions/upload-artifact@v4
        with:
          name: SimpMusic-macOS-Installer
          # Este comodín busca automáticamente el archivo .dmg sin importar en qué carpeta se generó
          path: '**/*.dmg'
          retention-days: 7
